SimpleCalculator/Models/Calculation.cs
using System.Data.Entity;
using System.ComponentModel.DataAnnotations;

namespace SimpleCalculator.Models
{
    public class Calculation
    {
            public int ID { get; set; }
            [Display(Name = "First Number")]
            public double Param1 { get; set; }
            [Display(Name = "Second Number")]
            public double Param2 { get; set; }
            [StringLength(1)]
            public string Operator { get; set; }
            public double? Result { get; set; }

    }

    public class CalculationDBContext : DbContext
    {
        public DbSet<Calculation> Calculations { get; set; }
    }
}

SimpleCalculator/Controllers/CalculationsController.cs
using System.Linq;
using System.Web.Mvc;
using SimpleCalculator.Models;

namespace SimpleCalculator.Controllers
{
    public class CalculationsController : Controller
    {
        private CalculationDBContext db = new CalculationDBContext();

        // GET: Calculations
        public ActionResult Index()
        {
            var calcs = db.Calculations.ToList();
            calcs.Reverse();
            ViewBag.hist = calcs;
            return View();
        }

        // POST: Calculations/Add
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add([Bind(Include = "ID,Param1,Param2")] Calculation calculation)
        {
            if (ModelState.IsValid)
            {
                calculation.Operator = "+";
                calculation.Result = calculation.Param1 + calculation.Param2;
                if (Create(calculation) == true)
                {
                    return RedirectToAction("Index");
                }
            }

            return View("Index", calculation);
        }

        // POST: Calculations/Subtract
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Subtract([Bind(Include = "ID,Param1,Param2")] Calculation calculation)
        {
            if (ModelState.IsValid)
            {
                calculation.Operator = "-";
                calculation.Result = calculation.Param1 - calculation.Param2;
                if (Create(calculation) == true)
                {
                    return RedirectToAction("Index");
                }
            }

            return View("Index", calculation);
        }

        // POST: Calculations/Multiply
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Multiply([Bind(Include = "ID,Param1,Param2")] Calculation calculation)
        {
            if (ModelState.IsValid)
            {
                calculation.Operator = "*";
                calculation.Result = calculation.Param1 * calculation.Param2;
                if (Create(calculation) == true)
                {
                    return RedirectToAction("Index");
                }
            }

            return View("Index", calculation);
        }

        // POST: Calculations/Divide
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Divide([Bind(Include = "ID,Param1,Param2")] Calculation calculation)
        {
            if (ModelState.IsValid)
            {
                calculation.Operator = "/";
                calculation.Result = calculation.Param1 / calculation.Param2;
                if (Create(calculation) == true)
                {
                    return RedirectToAction("Index");
                }

            }

            return View("Index", calculation);
        }

        // Creates history record of calculation and returns true if successful
        private bool Create([Bind(Include = "ID,Param1,Param2,Operator,Result")] Calculation calculation)
        {
            if (ModelState.IsValid)
            {
                db.Calculations.Add(calculation);
                db.SaveChanges();
                return true;
            }

            return false;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SimpleCalculator/Views/Calculations/Index.cshtml
@model SimpleCalculator.Models.Calculation

@* TODO: Implement toastr notifications for results *@
<h2>Calculator</h2>

@using (Html.BeginForm("", "Calculations", FormMethod.Post, htmlAttributes: new { @id = "calculator-form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Param1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Param1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Param1, "", new { @class = "text-danger" })
            </div>
        </div>
        <hr />
        <div id="operator-container" class="row">
            <div class="col-xs-3">
                <button id="Add" class="btn btn-lg btn-default font-weight-bold">+</button>
            </div>
            <div class="col-xs-3">
                <button id="Subtract" class="btn btn-lg btn-default font-weight-bold">-</button>
            </div>
          <div class="col-xs-3">
                <button id="Multiply" class="btn btn-lg btn-default font-weight-bold">*</button>
            </div>
            <div class="col-xs-3">
                <button id="Divide" class="btn btn-lg btn-default font-weight-bold">/</button>
            </div>
        </div>
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.Param2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Param2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Param2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group text-center">
            <div class="col-xs-12">
                <input type="submit" value="Calculate" class="btn btn-success" />
            </div>
        </div>
    </div>
}

@{ Html.RenderPartial("_History", (IEnumerable<SimpleCalculator.Models.Calculation>)ViewBag.hist);}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        function setOperator(id, url)
        {
            $('#calculator-form').attr('action', url);
            $('#operator-container div button').removeClass('btn-info').addClass('btn-default');
            $('#' + id).removeClass("btn-default").addClass('btn-info');
        }

        $('#Add').on('click', function (e) {
            e.preventDefault();
            setOperator(this.id, '@Url.Action("Add")');
        });
        $('#Subtract').on('click', function (e) {
            e.preventDefault();
            setOperator(this.id, '@Url.Action("Subtract")');
        });
        $('#Multiply').on('click', function (e) {
            e.preventDefault();
            setOperator(this.id, '@Url.Action("Multiply")');
        });
        $('#Divide').on('click', function (e) {
            e.preventDefault();
            setOperator(this.id, '@Url.Action("Divide")');
        });
    </script>
}

SimpleCalculator/Views/Calculations/_History.cshtml
@model IEnumerable<SimpleCalculator.Models.Calculation>

<h2>Results</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Param1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Operator)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Param2)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Result)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Param1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Operator)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Param2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Result)
            </td>
        </tr>
    }

</table>

SimpleCalculator/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Simple Calculator</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("Simple Calculator", "Index", "Calculations", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Simple Calculator</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>